<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <BaseOutputPath>D:\Prescriptoo\AuthenticationSystem\bin\Debug\net8.0\Plugins</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Dtos\ReturnDto\" />
    <Folder Include="Insfracture\Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="0.9.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.71" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiCallService\ApiCallService.csproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\Doctor\Doctor.csproj" />
    <ProjectReference Include="..\Entities\Entities.csproj" />
    <ProjectReference Include="..\PluginDIService\PluginDIService.csproj" />
    <ProjectReference Include="..\SharedService\SharedService.csproj" />
    <ProjectReference Include="..\Utility\Utility.csproj" />
  </ItemGroup>

</Project>

