<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <BaseOutputPath>D:\soowgood\SWCoreSystem\SWCoreSystem\AuthenticationSystem\bin\Debug\net8.0\Plugins</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Dtos\ReturnDto\" />
    <Folder Include="Insfracture\Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\Entities\Entities.csproj" />
    <ProjectReference Include="..\PluginDIService\PluginDIService.csproj" />
    <ProjectReference Include="..\SharedService\SharedService.csproj" />
    <ProjectReference Include="..\Utility\Utility.csproj" />
  </ItemGroup>

</Project>
